name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/kxt/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
